name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
  test_cov_console: ^0.2.2
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
