// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxExoJ9za4hUOFV_QPyigvim_yJ6Wp-4I',
    appId: '1:720197873130:web:730b7b186991a4822b9693',
    messagingSenderId: '720197873130',
    projectId: 'productsearch-d9788',
    authDomain: 'productsearch-d9788.firebaseapp.com',
    storageBucket: 'productsearch-d9788.appspot.com',
    measurementId: 'G-5P6XS8ND1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQGM3bE6QgHPomn3jSn6YwNZXB3KJKpk',
    appId: '1:720197873130:android:1b899f194e4df65d2b9693',
    messagingSenderId: '720197873130',
    projectId: 'productsearch-d9788',
    storageBucket: 'productsearch-d9788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM7khc5ZoUzz3Pg-7ABNOnAD5SClGJtYk',
    appId: '1:720197873130:ios:9158ff999d9294f82b9693',
    messagingSenderId: '720197873130',
    projectId: 'productsearch-d9788',
    storageBucket: 'productsearch-d9788.appspot.com',
    iosBundleId: 'com.example.productSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM7khc5ZoUzz3Pg-7ABNOnAD5SClGJtYk',
    appId: '1:720197873130:ios:9158ff999d9294f82b9693',
    messagingSenderId: '720197873130',
    projectId: 'productsearch-d9788',
    storageBucket: 'productsearch-d9788.appspot.com',
    iosBundleId: 'com.example.productSearch',
  );
}
