name: infrastructure
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  domain:
    path: ../domain
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
